// <auto-generated />
using System;
using AfgangTilgangApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AfgangTilgangApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240506132717_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AfgangTilgangApi.Models.AfgangTilgang", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("Aar")
                        .HasColumnType("int");

                    b.Property<int?>("Alder")
                        .HasColumnType("int");

                    b.Property<string>("Anmearkning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Billedfil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Efternavn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Familieno")
                        .HasColumnType("int");

                    b.Property<int?>("Fodeaar")
                        .HasColumnType("int");

                    b.Property<string>("Folieside")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fornavn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Haandtering")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hvorfraankommet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hvorhenrejst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HvoriJeavnfReg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Liste")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("No")
                        .HasColumnType("int");

                    b.Property<string>("Sleagtsnavn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sogn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SogneNo")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("AfgangTilgang");
                });
#pragma warning restore 612, 618
        }
    }
}
